services:
  - type: web
    name: ads-card-hub
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    nodeVersion: 18.19.1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://adscardhub.onrender.com
      - key: MERCADO_PAGO_ACCESS_TOKEN
        value: APP_USR-5147742804966612-051513-9214487adad4e450950cc9b6025d15ae-455035581
      - key: MERCADO_PAGO_WEBHOOK_SECRET
        value: 0b481b66ed6f5e978972fb9d55559a50b045d1fcb7b4bd3ed6e1e5d8f6d53490
      - key: MERCADO_PAGO_PUBLIC_KEY
        value: APP_USR-7c84a5b6-f245-43c6-832a-72efde71e4a9
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block 